### ISSUE TITLE
Carstream player overwrites other players

### ISSUE THREAD

**Issue by greenblueye** [thekirankumar/youtube-android-auto#19]
Hello I have a problem such that after opening carstream i can not use other default Android auto streaming apps such as Spotify or Google music. Carstream app overrites them. I can not switch to Spotify player after carstream openned.

**Comment by magna413** [comment]
I have exact same issue. 
Phone is OnePlus 5.

**Comment by bobybc** [comment]
I can confirm that too. I think its will be good if "background play" feature havs an option for disable/enable.
i really don't use it

**Comment by thekirankumar** [comment]
Need some more info. Are you saying that once a video is played on CarStream, switching to other apps doesnt play audio, or switching to other app itself is not possible ?
Additionally, if you dont play a video at all in the first time, then switching works ?
A video capture to understand the issue will help.

**Comment by bobybc** [comment]
i mean "switching to other apps doesnt play audio". i tried with new mirroring app https://github.com/slashmax/AAMirror

I build your app with commented tags for MyMediaBrowserService and the issue is gone :


```
<!-- service  android:enabled="true" android:exported="true" android:name=".service.MyMediaBrowserService"
            android:label="@string/app_name_player" >
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
                <action android:name="android.media.AUDIO_BECOMING_NOISY" />
                <action android:name="android.media.browse.MediaBrowserService" />
            </intent-filter>
        </service>
        <receiver android:name="android.support.v4.media.session.MediaButtonReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver -->
```

**Comment by thekirankumar** [comment]
MyMediaBrowserService is required for steering controls to work. Please try next version >1.7.3 when it gets released. It has a minor patch which might fix it

**Comment by bobybc** [comment]
Tested with 1.8.0 version - it works now w/o issues

**Comment by thekirankumar** [comment]
Awesome. Thank you for reporting back

**Comment by tig2017** [comment]
good afternoon, I have a problem similar to the others:
I installed version 1.8.2 but if I start the car stream ok I see the videos quietly, except the fact that if I try to write with the keyboard while driving I will not let me do it and tells me to pull over (I think it's normal, and so for our safety).
if I switch to the car stream reader (I prefer to listen only to the youtube music and I do not want to distract myself), the player freezes and does not allow me to listen to the youtube audio, and if I try to switch to spotify the problem is the same, not it makes me listen to audio and the radio becomes silent.
