### ISSUE TITLE
App Blocked Again

### ISSUE THREAD

**Issue by frankskywlker** [thekirankumar/youtube-android-auto#63]
For the life of me I can't get this to install again. Have had no issues in the past, but wiped my phone (Pixel 2 xl) and cannot get any of the versions or methods to work.

Have tried APK Editor Pro, step by step with instructions, but keep getting a parsing error during install (have never been able to get this method to work).

App Cloner succeeds and installs, but app is blocked and still not showing up on my Sync3.

Previously had Plex, etc. working great on version 1.7.2

TIA

**Comment by nameor123** [comment]
Did you select the right apk file it should read like this. "youtube_auto_v1.8.3.apk"  Did you press full edit when you select the apk? In the bottom right corner of the manifest? It should look like this <manifest xmlns:android="http://schemas.android.com/a.  Click on it.

Look for pacakage
The text should be this.
"com.google.android.kk"
Change to com.yourname.testapp
Press build on the right top 

install and your done

**Comment by nameor123** [comment]
You should not be getting errors at all

**Comment by frankskywlker** [comment]
Yes I believe so, here are screenshots of what I'm getting: https://imgur.com/a/l6d77

**Comment by nameor123** [comment]
There shouldn't be unknown when you build the package. Also I never get sign apk with key. Try uninstalling apk editor pro and delete carstream redownload carstream and app editor pro. Make sure you get the latest on both app editor pro and carstream. It would also be helpful you screenshot all the steps you did in the beginning

**Comment by shmykelsa** [comment]
Have you activated Unknown Sources on Android Auto?

**Comment by nameor123** [comment]
It can't be that he didnt allow unknown sources because he was able to get it working on his car before.But it wouldn't hurt to check on it.  It could be possible. he was able to build it But he's getting it before app editor pro builds it and he is successful building the apk file. Could you screenshot the whole installation process when you get the installion for app pro editor and carstream  to when you finish everything? Also try to allow unknown sources for Android auto and to do that you need to be in developer mode in android auto

**Comment by frankskywlker** [comment]
> Have you activated Unknown Sources on Android Auto?

That was it. Since I'd wiped my phone, I forgot about the all important step 1 - allow unknown sources in AA via developer mode. 

Thanks guys for the help!
